2018-08-24 16:30:37,457 INFO: Microblog startup [in C:\pythonprograms\web_apps\Full_Bucket\app\__init__.py:74]
2018-08-24 16:31:30,839 INFO: Microblog startup [in C:\pythonprograms\web_apps\Full_Bucket\app\__init__.py:74]
2018-08-24 16:31:48,123 INFO: Microblog startup [in C:\pythonprograms\web_apps\Full_Bucket\app\__init__.py:74]
2018-08-24 16:32:17,380 INFO: Microblog startup [in C:\pythonprograms\web_apps\Full_Bucket\app\__init__.py:74]
2018-08-24 16:32:31,359 INFO: Microblog startup [in C:\pythonprograms\web_apps\Full_Bucket\app\__init__.py:74]
2018-08-24 16:33:01,798 INFO: Microblog startup [in C:\pythonprograms\web_apps\Full_Bucket\app\__init__.py:74]
2018-08-28 11:11:43,268 INFO: Microblog startup [in C:\pythonprograms\web_apps\TLFB\app\__init__.py:74]
2018-08-28 12:39:43,963 INFO: Microblog startup [in C:\pythonprograms\web_apps\TLFB\app\__init__.py:74]
2018-08-28 12:46:26,857 INFO: Microblog startup [in C:\pythonprograms\web_apps\TLFB\app\__init__.py:74]
2018-08-28 12:46:38,091 INFO: Microblog startup [in C:\pythonprograms\web_apps\TLFB\app\__init__.py:74]
2018-08-28 12:51:24,812 INFO: Microblog startup [in C:\pythonprograms\web_apps\TLFB\app\__init__.py:74]
2018-08-28 12:51:34,398 ERROR: Exception on /index [GET] [in c:\users\adrian\appdata\local\programs\python\python36\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\adrian\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\adrian\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\adrian\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\adrian\appdata\local\programs\python\python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\adrian\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\adrian\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\adrian\appdata\local\programs\python\python36\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\pythonprograms\web_apps\TLFB\app\main\routes.py", line 46, in index
    prev_url=prev_url)
  File "c:\users\adrian\appdata\local\programs\python\python36\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\adrian\appdata\local\programs\python\python36\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\adrian\appdata\local\programs\python\python36\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\adrian\appdata\local\programs\python\python36\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\adrian\appdata\local\programs\python\python36\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\adrian\appdata\local\programs\python\python36\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\pythonprograms\web_apps\TLFB\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\pythonprograms\web_apps\TLFB\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\adrian\appdata\local\programs\python\python36\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\adrian\appdata\local\programs\python\python36\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\adrian\appdata\local\programs\python\python36\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\adrian\appdata\local\programs\python\python36\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "C:\pythonprograms\web_apps\TLFB\app\templates\base.html", line 23, in block "navbar"
    <li><a href="{{ url_for('quest.initial_questions.')}}">{{_('Questions')}}</a> </li>
  File "c:\users\adrian\appdata\local\programs\python\python36\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\adrian\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\adrian\appdata\local\programs\python\python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\adrian\appdata\local\programs\python\python36\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\users\adrian\appdata\local\programs\python\python36\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'quest.initial_questions.'. Did you mean 'bootstrap.static' instead?
2018-08-28 13:08:10,230 INFO: Microblog startup [in C:\pythonprograms\web_apps\TLFB\app\__init__.py:77]
